myex_backend/config/routes.rb
MyexBackend::Application.routes.draw do

  root :to => 'sessions#new'
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy', :via => :delete
  match '/login', :to => 'sessions#new'
  match ':member_id/share_score', to: 'shares#share_score'
  match ':member_id/share_record/:record_id', to: 'shares#share_record'
  resources :sessions do
    collection do
      get 'forget_password'
      post 'send_token'
      get 'reset'
      post 'reset_password'
    end
  end
  mount API::Root => '/'
  resources :administrators do
    member do
      get 'message_index'
      post 'message_create_all'
    end

    collection do
      get 'notices'
      get 'notice_show'
      post 'message_update_all'
      post 'notice_special_view'
      post 'message_create_special'
      get 'notice_all_member'
      post 'notice_all_member_create'
      post 'notice_special_member'
      post 'notice_special_member_create'
      get 'find_special_coach'
      post 'find_coaches'
      get 'find_special_member'

    end
  end
  
end

myex_backend/app/models/administrator.rb
class Administrator < ActiveRecord::Base
  attr_accessible :name, :email, :phone, :role, :token, :password, :password_confirmation, :last_login

  has_secure_password

  before_save :create_remember_token

  validates :name, :length => { :maximum => 50 }
  validates :phone, :presence => true, :uniqueness => true
  validates :password, :presence => true, :length => { :minimum => 6 }, :if => :password
  validates :password_confirmation, :presence => true, :if => :password_confirmation

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

myex_backend/app/controllers/administrators_controller.rb
#encoding: utf-8
class AdministratorsController < ApplicationController
  before_filter :signed_in

  def show
    begin
      @admin = Administrator.find(params[:id])
    rescue
      redirect_to (current_admin), :notice => "该用户不存在."
    end
  end

  def update
    @admin = Administrator.find(params[:id])
    if @admin != current_admin && current_admin.role.to_s != "高级管理员".to_s
      flash[:error] = "只有高级管理员才能修改其他管理员。"
      redirect_to @admin
    elsif params[:administrator][:password].to_s.empty? || params[:administrator][:password] != params[:administrator][:password_confirmation]
      flash[:error] = "密码错误。"
      redirect_to @admin
    elsif @admin && @admin.update_attributes(params[:administrator])
      flash[:success] = "管理员信息更新成功。"
      sign_in @admin
      redirect_to @admin
    else
      flash[:error] = "管理员信息更新失败。"
      redirect_to @admin
    end
  end

  def index
    @admins = Administrator.all
    @admins.delete(current_admin)
    @admin = Administrator.new
  end

  def create
    @admin = Administrator.new(params[:administrator])
    if current_admin.role != "高级管理员"
      flash[:success] = "只有高级管理员才能创建新管理员。"
      redirect_to current_admin
    elsif @admin.save
      flash[:success] = "管理员创建成功。"
      redirect_to administrators_path
    else
      flash[:error] = "管理员创建失败。"
      redirect_to administrators_path
    end
  end

  def destroy
    @admin = Administrator.find(params[:id])
    if @admin.destroy
      flash[:success] = "管理员删除成功。"
      redirect_to administrators_path
    else
      flash[:error] = "管理员创建失败。"
      redirect_to administrators_path
    end
  end

  def message_index
    @notice = Notice.new
  end

  def message_create_all
    @coaches = Coach.all
    coaches = ""
    @coaches.each do |coach|
      coaches << coach.phone + ";"
    end
    @notice = Notice.new(title:params[:notice][:title], content:params[:notice][:content], category:params[:notice][:category], coach_phone:coaches, coach_phone_array:coaches)
    if @notice.save
      sendno = Time.now.to_i
      receiver_value_coach = coaches.gsub(/;/, ',')
      input_coach = sendno.to_s + I18n.t('.jpush.config.receiver_type').to_s + receiver_value_coach.to_s + I18n.t('.jpush.config.master_secret_coach').to_s
      md5_coach = Digest::MD5.hexdigest(input_coach)
      send_description = "创建新消息"
      n_content = "标题：#{params[:notice][:title]};内容：#{params[:notice][:content]}"
      n_extras = Hash[:type => params[:notice][:category]]
      msg_content = Hash[:n_content => n_content, :n_extras => n_extras].to_json
      output_coach = Net::HTTP.post_form(URI.parse(I18n.t('.jpush.config.uri')),
                                                      :sendno => sendno,
                                                      :app_key => I18n.t('.jpush.config.app_key_coach'),
                                                      :receiver_type => I18n.t('.jpush.config.receiver_type'),
                                                      :receiver_value => receiver_value_coach,
                                                      :verification_code => md5_coach,
                                                      :msg_type => I18n.t('.jpush.config.msg_type'),
                                                      :msg_content => msg_content,
                                                      :send_description => send_description,
                                                      :time_to_live => I18n.t('.jpush.config.time_to_live'),
                                                      :platform => I18n.t('.jpush.config.platform'))
      flash[:success] = "消息发送成功。"
      redirect_to notices_administrators_path
    else
      flash[:error] = "消息发送失败。"
      redirect_to notices_administrators_path
    end
  end

  def notices
    @notices = Notice.paginate(:page => params[:page], :per_page => 30)
  end

  def notice_show
    @notice = Notice.find(params[:format])
  end

  def notice_special_view
    @notice = Notice.new
    @coaches = Coach.where("province like ? AND city like ? AND profession like ? AND gender like ?", "%#{params[:coach][:province]}%", "%#{params[:coach][:city]}%", "%#{params[:coach][:profession]}%", "%#{params[:coach][:gender]}%")
  end

  def message_create_special
    coaches = ""
    params[:phones].each do |phone|
      coaches << phone + ";"
    end
    @notice = Notice.new(title:params[:notice][:title], content:params[:notice][:content], category:params[:notice][:category], coach_phone:coaches, coach_phone_array:coaches)
    if @notice.save
      sendno = Time.now.to_i
      receiver_value_coach = coaches.gsub(/;/, ',')
      input_coach = sendno.to_s + I18n.t('.jpush.config.receiver_type').to_s + receiver_value_coach.to_s + I18n.t('.jpush.config.master_secret_coach').to_s
      md5_coach = Digest::MD5.hexdigest(input_coach)
      send_description = "创建新消息"
      n_content = "标题：#{params[:notice][:title]};内容：#{params[:notice][:content]}"
      n_extras = Hash[:type => params[:notice][:category]]
      msg_content = Hash[:n_content => n_content, :n_extras => n_extras].to_json
      output_coach = Net::HTTP.post_form(URI.parse(I18n.t('.jpush.config.uri')),
                                                      :sendno => sendno,
                                                      :app_key => I18n.t('.jpush.config.app_key_coach'),
                                                      :receiver_type => I18n.t('.jpush.config.receiver_type'),
                                                      :receiver_value => receiver_value_coach,
                                                      :verification_code => md5_coach,
                                                      :msg_type => I18n.t('.jpush.config.msg_type'),
                                                      :msg_content => msg_content,
                                                      :send_description => send_description,
                                                      :time_to_live => I18n.t('.jpush.config.time_to_live'),
                                                      :platform => I18n.t('.jpush.config.platform'))
      flash[:success] = "消息发送成功。"
      redirect_to notices_administrators_path
    else
      flash[:error] = "消息发送失败。"
      redirect_to notices_administrators_path
    end
  end

  def notice_all_member
    @notice = Notice.new
  end

  def notice_all_member_create
    @members = Member.all
    phones = ""
    @members.each do |member|
      phones << member.phone + ";"
    end
    @notice = Notice.new(title:params[:notice][:title], content:params[:notice][:content], category:params[:notice][:category], member_phone:phones, member_phone_array:phones)
    if @notice.save
      sendno = Time.now.to_i
      receiver_value_member = phones.gsub(/;/, ',')
      input_member = sendno.to_s + I18n.t('.jpush.config.receiver_type').to_s + receiver_value_member.to_s + I18n.t('.jpush.config.master_secret_member').to_s
      md5_member = Digest::MD5.hexdigest(input_member)
      send_description = "创建新消息"
      n_content = "标题：#{params[:notice][:title]};内容：#{params[:notice][:content]}"
      n_extras = Hash[:type => params[:notice][:category]]
      msg_content = Hash[:n_content => n_content, :n_extras => n_extras].to_json
      output_member = Net::HTTP.post_form(URI.parse(I18n.t('.jpush.config.uri')),
                                                      :sendno => sendno,
                                                      :app_key => I18n.t('.jpush.config.app_key_member'),
                                                      :receiver_type => I18n.t('.jpush.config.receiver_type'),
                                                      :receiver_value => receiver_value_member,
                                                      :verification_code => md5_member,
                                                      :msg_type => I18n.t('.jpush.config.msg_type'),
                                                      :msg_content => msg_content,
                                                      :send_description => send_description,
                                                      :time_to_live => I18n.t('.jpush.config.time_to_live'),
                                                      :platform => I18n.t('.jpush.config.platform'))
      flash[:success] = "消息发送成功。"
      redirect_to notices_administrators_path
    else
      flash[:error] = "消息发送失败。"
      redirect_to notices_administrators_path
    end
  end

  def notice_special_member
    @notice = Notice.new
    @members = Member.where("province like ? AND city like ? AND gender like ?", "%#{params[:member][:province]}%", "%#{params[:member][:city]}%", "%#{params[:member][:gender]}%")
  end

  def notice_special_member_create
    phones = ""
    params[:phones].each do |phone|
      phones << phone + ";"
    end
    @notice = Notice.new(title:params[:notice][:title], content:params[:notice][:content], category:params[:notice][:category], member_phone:phones, member_phone_array:phones)
    if @notice.save
      sendno = Time.now.to_i
      receiver_value_member = phones.gsub(/;/, ',')
      input_member = sendno.to_s + I18n.t('.jpush.config.receiver_type').to_s + receiver_value_member.to_s + I18n.t('.jpush.config.master_secret_member').to_s
      md5_member = Digest::MD5.hexdigest(input_member)
      send_description = "创建新消息"
      n_content = "标题：#{params[:notice][:title]};内容：#{params[:notice][:content]}"
      n_extras = Hash[:type => params[:notice][:category]]
      msg_content = Hash[:n_content => n_content, :n_extras => n_extras].to_json
      output_member = Net::HTTP.post_form(URI.parse(I18n.t('.jpush.config.uri')),
                                                      :sendno => sendno,
                                                      :app_key => I18n.t('.jpush.config.app_key_member'),
                                                      :receiver_type => I18n.t('.jpush.config.receiver_type'),

myex_backend/app/helpers/administrators_helper.rb
module AdministratorsHelper
end

myex_backend/app/views/administrators/find_special_coach.html.erb
<%= render 'shared/main2' %>

<div class="wrapper_small">
    <div class="op_page">
        <div class="return">
        </div>
        <div class="content_form g_border">
            <div class="hd g_box">
                <div class="op_list g_tp_10">
                    <%= link_to "给所有教练发送通知", message_index_administrator_path(current_admin)%>
                    <%= link_to "给特定教练发送通知", find_special_coach_administrators_path, :class => "current" %>
                    <%= link_to "给所有会员发送通知", notice_all_member_administrators_path %>
                    <%= link_to "给特定会员发送通知", find_special_member_administrators_path %>
                    <%= link_to "通知列表", notices_administrators_path %>
                </div>
            </div>

            <div class="bd no_tp">
              <div class="form">
                  <%= form_for @coach, :url => {:action => 'notice_special_view'}  do |f| %>
                    <div class="g_input">
                      <%= f.label :province, "省", :class =>  "gi_label" %>
                      <%= f.text_field :province, :class => "gi_input", :type => "text", :placeholder => "" %>
                    </div>
                    <div class="g_input">
                      <%= f.label :city, "市", :class =>  "gi_label" %>
                      <%= f.text_field :city, :class => "gi_input", :type => "text", :placeholder => "" %>
                    </div>
                    
                    <div class="g_input">
                      <%= f.label :profession, "专业方向", :class =>  "gi_label" %>
                      <%= f.text_field :profession, :class => "gi_input", :type => "text", :placeholder => "" %>
                    </div>
                        <div class="g_box", style= "margin-top:15px;">
                        <%= f.label :gender, "性别", :class => "gi_label" %>
                        <%= f.select :gender, ["","男", "女"], :class => "gi_input" %>
                    </div>

                    <div class="item align_right">
                        <%= f.submit "查找", :class => "g_btn_blue" %>
                    </div>
                  <% end %>
                </div>

            </div>
            



        </div>
    </div>
</div>

myex_backend/app/views/administrators/find_special_member.html.erb
<%= render 'shared/main2' %>

<div class="wrapper_small">
    <div class="op_page">
        <div class="return">
        </div>
        <div class="content_form g_border">
            <div class="hd g_box">
                <div class="op_list g_tp_10">
                    <%= link_to "给所有教练发送通知", message_index_administrator_path(current_admin)%>
                    <%= link_to "给特定教练发送通知", find_special_coach_administrators_path %>
                    <%= link_to "给所有会员发送通知", notice_all_member_administrators_path %>
                    <%= link_to "给特定会员发送通知", find_special_member_administrators_path, :class => "current" %>
                    <%= link_to "通知列表", notices_administrators_path %>
                </div>
            </div>

            <div class="bd no_tp">
              <div class="form">
                  <%= form_for @member, :url => {:action => 'notice_special_member'}  do |f| %>
                    <div class="g_input">
                      <%= f.label :province, "省", :class =>  "gi_label" %>
                      <%= f.text_field :province, :class => "gi_input", :type => "text", :placeholder => "" %>
                    </div>
                    <div class="g_input">
                      <%= f.label :city, "市", :class =>  "gi_label" %>
                      <%= f.text_field :city, :class => "gi_input", :type => "text", :placeholder => "" %>
                    </div>
                    
                    <div class="g_box", style= "margin-top:15px;">
                        <%= f.label :gender, "性别", :class => "gi_label" %>
                        <%= f.select :gender, ["","男", "女"], :class => "gi_input" %>
                    </div>

                    <div class="item align_right">
                        <%= f.submit "查找", :class => "g_btn_blue" %>
                    </div>
                  <% end %>
                </div>

            </div>
            



        </div>
    </div>
</div>

myex_backend/app/views/administrators/index.html.erb
<%= render 'shared/main' %>

<div class="wrapper_small">
    <div class="op_page">
        <div class="return">
        </div>
        <div class="content_form g_border">
            <div class="hd g_box">
                <div class="op_list g_tp_10">
                    <%= link_to "个人信息", current_admin %>
                    <%= link_to "操作员信息", administrators_path, :class => "current" %>
                </div>
            </div>

            <div class="bd no_tp">
              <%= form_for @admin do |f| %>
                <div class="g_input">
                  <%= f.label :name, "用户名", :class =>  "gi_label" %>
                  <%= f.text_field :name, :class => "gi_input", :type => "text", :placeholder => "" %>
                </div>
                <div class="g_input">
                  <%= f.label :phone, "手机号", :class =>  "gi_label" %>
                  <%= f.text_field :phone, :class => "gi_input", :type => "text", :placeholder => "" %>
                </div>
                <div class="g_input">
                  <%= f.label :email, "邮箱", :class =>  "gi_label" %>
                  <%= f.text_field :email, :class => "gi_input", :type => "text", :placeholder => "" %>
                </div>
                <div class="g_input">
                    <%= f.label :password, "密码", :class =>  "gi_label" %>
                    <%= f.password_field :password, :class => "gi_input", :type => "password", :placeholder => "" %>
                </div>
                <div class="g_input">
                    <%= f.label :password_confirmation, "密码确认", :class =>  "gi_label" %>
                    <%= f.password_field :password_confirmation, :class => "gi_input", :type => "password", :placeholder => "" %>
                </div>
                <br/>
                <div class="g_box">
                    <%= f.label :role, "管理员权限 | ", :class => "gi_label" %>
                    <%= f.select :role, ["高级管理员", "初级管理员"], :class => "gi_input" %>

                </div>

                <div class="item align_right">
                    <%= f.submit "　创建　", :class => "g_btn_blue" %>
                </div>
              <% end %>

            </div>
            

            <!--phone Start -->
                <div id="tokenContainer">
                    <div class="block">
                        <p class="title">操作员</p>
                        <% @admins.each do |admin| %>
                          <p><strong><%= link_to admin.name, admin %></strong></p>
                        <% end %>
                    </div>
                </div>


        </div>
    </div>
</div>

myex_backend/app/views/administrators/message_index.html.erb
<%= render 'shared/main2' %>

<div class="wrapper_small">
    <div class="op_page">
        <div class="return">
        </div>
        <div class="content_form g_border">
            <div class="hd g_box">
                <div class="op_list g_tp_10">
                    <%= link_to "给所有教练发送通知", message_index_administrator_path(current_admin), :class => "current"%>
                    <%= link_to "给特定教练发送通知", find_special_coach_administrators_path %>
                    <%= link_to "给所有会员发送通知", notice_all_member_administrators_path %>
                    <%= link_to "给特定会员发送通知", find_special_member_administrators_path %>
                    <%= link_to "通知列表", notices_administrators_path %>
                </div>
            </div>

            <div class="bd no_tp">
              <%= form_for @notice, :url => {:action => 'message_create_all'}  do |f| %>
                <div class="g_input">
                  <%= f.label :title, "标题", :class =>  "gi_label" %>
                  <%= f.text_field :title, :class => "gi_input", :type => "text", :placeholder => "" %>
                </div>
                <div class="g_input">
                  <%= f.label :content, "内容", :class =>  "gi_label" %>
                  <%= f.text_area :content, :class => "gi_input", :type => "text", :placeholder => "", :style => "height:180px;" %>
                </div>
                <br/>
                <div class="g_box", style= "margin-top:150px;">
                    <%= f.label :category, "通知类型 | ", :class => "gi_label" %>
                    <%= f.select :category,["系统通知"，"培训通知"，"招聘通知"， "其他通知"] :class => "gi_input" %>
                </div>

                <div class="item align_right">
                    <%= f.submit "　创建　", :class => "g_btn_blue" %>
                </div>
              <% end %>

            </div>
            



        </div>
    </div>
</div>

myex_backend/app/views/administrators/notice_all_member.html.erb
<%= render 'shared/main2' %>

<div class="wrapper_small">
    <div class="op_page">
        <div class="return">
        </div>
        <div class="content_form g_border">
            <div class="hd g_box">
                <div class="op_list g_tp_10">
                    <%= link_to "给所有教练发送通知", message_index_administrator_path(current_admin)%>
                    <%= link_to "给特定教练发送通知", find_special_coach_administrators_path %>
                    <%= link_to "给所有会员发送通知", notice_all_member_administrators_path, :class => "current" %>
                    <%= link_to "给特定会员发送通知", find_special_member_administrators_path %>
                    <%= link_to "通知列表", notices_administrators_path %>
                </div>
            </div>

            <div class="bd no_tp">
              <%= form_for @notice, :url => {:action => 'notice_all_member_create'}  do |f| %>
                <div class="g_input">
                  <%= f.label :title, "标题", :class =>  "gi_label" %>
                  <%= f.text_field :title, :class => "gi_input", :type => "text", :placeholder => "" %>
                </div>
                <div class="g_input">
                  <%= f.label :content, "内容", :class =>  "gi_label" %>
                  <%= f.text_area :content, :class => "gi_input", :type => "text", :placeholder => "", :style => "height:180px;" %>
                </div>
                <br/>
                <div class="g_box", style= "margin-top:150px;">
                    <%= f.label :category, "通知类型 | ", :class => "gi_label" %>
                    <%= f.select :category, ["系统通知"，"培训通知"，"招聘通知"， "其他通知"], :class => "gi_input" %>
                </div>

                <div class="item align_right">
                    <%= f.submit "　创建　", :class => "g_btn_blue" %>
                </div>
              <% end %>

            </div>
            



        </div>
    </div>
</div>

myex_backend/app/views/administrators/notice_show.html.erb
<%= render 'shared/main2' %>

<div class="wrapper_small">
    <div class="op_page">
        <div class="return">
        </div>
        <div class="content_form g_border">
            <div class="hd g_box">
                <div class="op_list g_tp_10">
                    <%= link_to "给所有教练发送通知", message_index_administrator_path(current_admin) %>
                    <%= link_to "给特定教练发送通知", find_special_coach_administrators_path %>
                    <%= link_to "给所有会员发送通知", notice_all_member_administrators_path %>
                    <%= link_to "给特定会员发送通知", find_special_member_administrators_path %>
                    <%= link_to "通知列表", notices_administrators_path %>
                </div>
            </div>

            <div class="bd no_tp">
              <%= form_for @notice, :url => {:action => 'message_update_all'}  do |f| %>
                <div class="g_input">
                  <%= f.label :title, "标题", :class =>  "gi_label" %>
                  <%= f.text_field :title, :class => "gi_input", :type => "text", :placeholder => "", :disabled => true %>
                </div>
                <div class="g_input">
                  <%= f.label :content, "内容", :class =>  "gi_label" %>
                  <%= f.text_area :content, :class => "gi_input", :type => "text", :placeholder => "", :style => "height:180px;", :disabled => true  %>
                </div>
                <br/>
                <div class="g_input", style= "margin-top:150px;">
                  <%= f.label :category, "通知类型 | ", :class =>  "gi_label" %>
                  <%= f.text_field :category, :class => "gi_input", :type => "text", :placeholder => "", :disabled => true  %>
                </div>
                <div class="g_input">
                  <%= f.label :coach_phone_array, "教练手机号", :class =>  "gi_label" %>
                  <%= f.text_field :coach_phone_array, :class => "gi_input", :type => "text", :placeholder => "", :disabled => true  %>
                </div>
                <div class="g_input">
                  <%= f.label :member_phone_array, "会员手机号", :class =>  "gi_label" %>
                  <%= f.text_field :member_phone_array, :class => "gi_input", :type => "text", :placeholder => "", :disabled => true  %>
                </div>
                
              <% end %>

            </div>
            



        </div>
    </div>
</div>

myex_backend/app/views/administrators/notice_special_member.html.erb
<%= render 'shared/main2' %>

<div class="wrapper_small">
    <div class="op_page">
        <div class="return">
        </div>
        <div class="content_form g_border">
            <div class="hd g_box">
                <div class="op_list g_tp_10">
                    <%= link_to "给所有教练发送通知", message_index_administrator_path(current_admin)%>
                    <%= link_to "给特定教练发送通知", find_special_coach_administrators_path %>
                    <%= link_to "给所有会员发送通知", notice_all_member_administrators_path %>
                    <%= link_to "给特定会员发送通知", find_special_member_administrators_path, :class => "current" %>
                    <%= link_to "通知列表", notices_administrators_path %>
                </div>
            </div>

            <div class="bd no_tp">
              <%= form_for @notice, :url => {:action => 'notice_special_member_create'}  do |f| %>
                <div class="g_input">
                  <%= f.label :title, "标题", :class =>  "gi_label" %>
                  <%= f.text_field :title, :class => "gi_input", :type => "text", :placeholder => "" %>
                </div>
                <div class="g_input">
                  <%= f.label :content, "内容", :class =>  "gi_label" %>
                  <%= f.text_area :content, :class => "gi_input", :type => "text", :placeholder => "", :style => "height:180px;" %>
                </div>
                <br/>
                <div class="g_box", style= "margin-top:150px;">
                    <%= f.label :category, "通知类型 | ", :class => "gi_label" %>
                    <%= f.select :category, ["系统通知"，"培训通知"，"招聘通知"， "其他通知"], :class => "gi_input" %>
                </div>

                <div id="tokenContainer">
                    <div class="block">
                        <p class="title">通知</p>
                        <li><strong><input type="checkbox" id="select_all"/>选择全部</li></strong>
                        <% @members.each do |member| %>
                          <li><strong><%= check_box_tag "phones[]", member.phone, false, class: 'box' %>  会员姓名：<%= member.name %> | 手机号：<%= member.phone %></strong></li>
                        <% end %>
                    </div>
                </div>

                <div class="item align_right">
                    <%= f.submit "　创建　", :class => "g_btn_blue" %>
                </div>
              <% end %>

            </div>
            



        </div>
    </div>
</div>

myex_backend/app/views/administrators/notice_special_view.html.erb
<%= render 'shared/main2' %>

<div class="wrapper_small">
    <div class="op_page">
        <div class="return">
        </div>
        <div class="content_form g_border">
            <div class="hd g_box">
                <div class="op_list g_tp_10">
                    <%= link_to "给所有教练发送通知", message_index_administrator_path(current_admin)%>
                    <%= link_to "给特定教练发送通知", find_special_coach_administrators_path, :class => "current" %>
                    <%= link_to "给所有会员发送通知", notice_all_member_administrators_path %>
                    <%= link_to "给特定会员发送通知", find_special_member_administrators_path %>
                    <%= link_to "通知列表", notices_administrators_path %>
                </div>
            </div>

            <div class="bd no_tp">
              <%= form_for @notice, :url => {:action => 'message_create_special'}  do |f| %>
                <div class="g_input">
                  <%= f.label :title, "标题", :class =>  "gi_label" %>
                  <%= f.text_field :title, :class => "gi_input", :type => "text", :placeholder => "" %>
                </div>
                <div class="g_input">
                  <%= f.label :content, "内容", :class =>  "gi_label" %>
                  <%= f.text_area :content, :class => "gi_input", :type => "text", :placeholder => "", :style => "height:180px;" %>
                </div>
                <br/>
                <div class="g_box", style= "margin-top:150px;">
                    <%= f.label :category, "通知类型 | ", :class => "gi_label" %>
                    <%= f.select :category, ["系统通知"，"培训通知"，"招聘通知"， "其他通知"], :class => "gi_input" %>
                </div>

                <div id="tokenContainer">
                    <div class="block">
                        <p class="title">通知</p>
                        <li><strong><input type="checkbox" id="select_all"/>选择全部</li></strong>
                        <% @coaches.each do |coach| %>
                          <li><strong><%= check_box_tag "phones[]", coach.phone, false, class: 'box' %>  教练姓名：<%= coach.name %> | 手机号：<%= coach.phone %></strong></li>
                        <% end %>
                    </div>
                </div>

                <div class="item align_right">
                    <%= f.submit "　创建　", :class => "g_btn_blue" %>
                </div>
              <% end %>

            </div>
            



        </div>
    </div>
</div>

myex_backend/app/views/administrators/notices.html.erb
<%= render 'shared/main2' %>

<div class="wrapper_small">
    <div class="op_page">
        <div class="return">
        </div>
        <div class="content_form g_border">
            <div class="hd g_box">
                <div class="op_list g_tp_10">
                    <%= link_to "给所有教练发送通知", message_index_administrator_path(current_admin) %>
                    <%= link_to "给特定教练发送通知", find_special_coach_administrators_path %>
                    <%= link_to "给所有会员发送通知", notice_all_member_administrators_path %>
                    <%= link_to "给特定会员发送通知", find_special_member_administrators_path %>
                    <%= link_to "通知列表", notices_administrators_path, :class => "current" %>
                </div>
            </div>

                <div id="tokenContainer">
                    <div class="block">
                        <p class="title">通知</p>
                        <% @notices.each do |notice| %>
                          <li><strong><%= link_to "#{notice.title}", notice_show_administrators_path(notice) %></strong></li>
                        <% end %>
                    </div>
                </div>
                <%= will_paginate @notices %>

        </div>
    </div>
</div>