myex_backend/config/routes.rb
MyexBackend::Application.routes.draw do

  root :to => 'sessions#new'
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy', :via => :delete
  match '/login', :to => 'sessions#new'
  match ':member_id/share_score', to: 'shares#share_score'
  match ':member_id/share_record/:record_id', to: 'shares#share_record'
  resources :sessions do
    collection do
      get 'forget_password'
      post 'send_token'
      get 'reset'
      post 'reset_password'
    end
  end
  mount API::Root => '/'
  resources :administrators do
    member do
      get 'message_index'
      post 'message_create_all'
    end

    collection do
      get 'notices'
      get 'notice_show'
      post 'message_update_all'
      post 'notice_special_view'
      post 'message_create_special'
      get 'notice_all_member'
      post 'notice_all_member_create'
      post 'notice_special_member'
      post 'notice_special_member_create'
      get 'find_special_coach'
      post 'find_coaches'
      get 'find_special_member'

    end
  end
  
end

myex_backend/app/views/shared/_main.html.erb
<div class="g_header">
    <div class="inner">
        <h1 style="display: none;"><%= image_tag "slogo.png" %> 51练 - <span>管理员客户端</span></h1>
        <h1><strong>51练</strong> 管理员客户端</h1>
        <p class="user_info">欢迎，<%= current_admin.name %> , <%= link_to "退出登录", logout_path, :method => "delete", :confirm => "确定要退出登录吗？" %></p>
        <p class="login_time">上次登录时间：<%= current_admin.last_login.try(:strftime, "%Y.%m.%d %H:%M") %></p>
        <ul class="nav">
            <li><%= link_to "发送消息", message_index_administrator_path(current_admin) %></li>
            <li class="current"><%= link_to "管理员信息", administrator_path(current_admin) %></li>
        </ul>
        </ul>
    </div>
</div>

myex_backend/app/views/shared/_main2.html.erb
<div class="g_header">
    <div class="inner">
        <h1 style="display: none;"><%= image_tag "slogo.png" %> 51练 - <span>管理员客户端</span></h1>
        <h1><strong>51练</strong> 管理员客户端</h1>
        <p class="user_info">欢迎，<%= current_admin.name %> , <%= link_to "退出登录", logout_path, :method => "delete", :confirm => "确定要退出登录吗？" %></p>
        <p class="login_time">上次登录时间：<%= current_admin.last_login.try(:strftime, "%Y.%m.%d %H:%M") %></p>
        <ul class="nav">
            <li class="current"><%= link_to "发送消息", message_index_administrator_path(current_admin)  %></li>
            <li><%= link_to "管理员信息", administrator_path(current_admin) %></li>
        </ul>
        </ul>
    </div>
</div>